### ISSUE TITLE
Close to tray?

### ISSUE THREAD

**Issue by LeSnake04** [liuyug/alltray#2]
Is it possible to add a close to tray option, that allows me to close the window like every other windows, but the program dont stops until I close it in the tray bar?

**Comment by liuyug** [comment]
click "save & tray" button in dialog that will run console application in background and show tray icon

**Comment by liuyug** [comment]
and screenshot is old, "save & tray" is new button.

**Comment by LeSnake04** [comment]
Just realized that this is the wrong Alltray.

Sorry for inconvenience .-.
